### ISSUE TITLE
jackson-core-2.10.5 dependency tree doesn't contains jackson-core-2.3.1 as a dependency and how it's possible to depend on the same source?

### ISSUE THREAD

**Issue by karthik0411** [FasterXML/jackson-core#701] opened 2021-05-21 05:42 UTC
**mvn dependency:tree**

com.fasterxml.jackson.core:jackson-core:bundle:2.10.5
\- junit:junit:jar:4.12:test
   \- org.hamcrest:hamcrest-core:jar:1.3:test

but when we try a build it's fetching jackson-core-2.3.1 ,jackson-annotations-2.3.1,jackson-databind-2.3.1 as a dependency
in local repository (.m2/repositories).

How a framework depend on it's own subversion?

**Comment by cowtowncoder** [comment] 2021-05-26 17:23
Jackson components do not depend on different versions of other Jackson components: dependencies are for the same minor version, at least, always.

So the problem is probably with your Maven project definition: try to see where old dependencies come from.

But note that `jackson-core` does NOT depend on either `jackson-annotations` or `jackson-databind` (jackson-databind does depend on jackson-core and jackson-annotations).

You may consider using Maven import of `jackson-bom` to get a consistent set of versions.

**Comment by stevenschlansker** [comment] 2022-01-04 03:36
We have observed this as well, our large dependency tree has many transitive dependencies (through libraries) on different versions of jackson. So Maven will download at least the `pom` for all versions referred to, even though only a single version is ever selected (via `jackson-bom` in our case) to be included in any classpath.

**Comment by GedMarc** [comment] 2022-01-04 03:44
should import the jackson bom using dependency-management for the version that will be used / but keep in mind osgi and/or classloader encapsulations, some libraries may be using old version for that reason - and are configured as such in some EE containers

**Comment by cowtowncoder** [comment] 2022-01-04 04:43
Back to the original question: Maven dependency management system must download various versions of all transitive dependencies to resolve actual versions used. This does not mean that Jackson itself depends on different versions; nor that multiple versions would be used. They just need to be resolved, specifically metadata from `pom.xml`s involved.

With that, I'll close this non-issue issue.

**Closed by cowtowncoder** 2022-01-04 04:43 UTC
