### ISSUE TITLE
Jackson Buffer Recycler not release object    

### ISSUE THREAD

**Issue by rits883** [FasterXML/jackson-core#622] opened 2020-05-26 14:56 UTC
Hi , 
We are using  Jackson lib  version 2.9.9  for parsing object. While doing memory analysis we found 
Jackson  objects are holding resources due to BufferRecycler 

1.For char objects :-  _charBuffers in com.fasterxml.jackson.core.util.BufferRecycler
2.For byte objects:-  _byteBuffers in com.fasterxml.jackson.core.util.BufferRecycler
3.For int objects :-    com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer$TableInfo

Please help us with possible solution if it is already fixed any version please update

**Comment by rits883** [comment] 2020-05-26 15:09
![Char_issueUpdate](https://user-images.githubusercontent.com/44515254/82916657-f18e5c80-9f8f-11ea-983e-a6f5348cdbc6.png)

![intErrorValueHold](https://user-images.githubusercontent.com/44515254/82917392-fef81680-9f90-11ea-8b47-80181258a62a.PNG)

**Comment by rits883** [comment] 2020-05-26 15:11
![byte_error](https://user-images.githubusercontent.com/44515254/82917671-55655500-9f91-11ea-8c7c-52565afb72ad.PNG)

**Comment by rits883** [comment] 2020-05-26 16:12
![char_issue_update_1](https://user-images.githubusercontent.com/44515254/82924303-c4df4280-9f99-11ea-8a53-ae941678e815.png)

**Comment by rits883** [comment] 2020-05-26 16:13
![int4k](https://user-images.githubusercontent.com/44515254/82924410-eb04e280-9f99-11ea-95ea-05fd013528ab.PNG)

**Comment by cowtowncoder** [comment] 2020-05-26 17:00
Yes, this is by design: `BufferRecycler` is used -- as name implies -- to recycle input and output buffers using `SoftReference`. It is meant to hold on to those, unless JVM deems it necessary to clear such references.

But if you think it is worth the additional allocation overhead (or if platform has broken `SoftReference` implementation, like Android seems to have), you may disable this using

    jsonFactory.disable(JsonFactory.Feature.USE_THREAD_LOCAL_FOR_BUFFER_RECYCLING);

**Comment by rits883** [comment] 2020-05-27 04:47
Thanks for you clarification on Buffer Recycling .
We also observed that int object  leaking some memory due to byteQyadsCanonicalizer . is there any way to prevent this .

**Comment by cowtowncoder** [comment] 2020-05-27 16:47
It is good to be careful with terminology: memory leak would refer to some memory unused and unreachable; I suspect what you see is regular retention. `ByteQuadsCanonicalizer` will create and reuse Symbols (property names) across by parsers created by same `JsonFactory` (instance of which should be reused, usually done by `ObjectMapper` holding onto reference).
Number of symbols is limited so it does not grow indefinitely (even if there is unbounded number of distinct names), but for common use cases tends to grow slightly over time.

You can disable this reuse with `JsonFactory.Feature.CANONICALIZE_FIELD_NAMES` (and if you do that, you probably also want to disable `JsonFactory.Feature.INTERN_FIELD_NAMES`), but this is likely to reduce performance somewhat for common use cases.

**Comment by cowtowncoder** [comment] 2020-08-19 19:00
Not sure if there is anything else to do here, closing.

**Closed by cowtowncoder** 2020-08-19 19:00 UTC
