### ISSUE TITLE
http://wiki.fasterxml.com/JacksonHome is broken

### ISSUE THREAD

**Issue by damnhandy** [FasterXML/jackson-core#319] opened 2016-09-06 18:44 UTC
The host http://wiki.fasterxml.com does not seem available and the majority of Google searches and links from the GitHub projects pages still ink here. It's been this way for a few weeks now. Is this site no longer available? If so , do the docs live somewhere else now?

**Comment by cowtowncoder** [comment] 2016-09-06 21:17
This is not a bug for streaming API, closing. Unavailability itself has been reported, known, no ETA when or if it can be fixed.

**Closed by cowtowncoder** 2016-09-06 21:17 UTC
