### ISSUE TITLE
jackson-core-2.15.0-rc1 fails to resolve in OSGi

### ISSUE THREAD

**Issue by rakeshk15** [FasterXML/jackson-core#956] opened 2023-03-21 01:46 UTC
Jackson core is importing this new package - **ch.randelshofer.fastdoubleparser** which is causing the bundle to remain unresolved in OSGi environments.

Seems like it is a new dependency in v2.15 which requires the OSGi users to install it as well to use the version v2.15.

This is a breaking change and API incompatible.

Mitigation:

Not sure what is being used from this library, if that is optional then we can make this package import as optional.

If not, then we can inline the dependency using maven plugins (maven-bundle-plugin/bnd-maven-plugin/maven-shade-plugin)

**Comment by cowtowncoder** [comment] 2023-03-21 02:09
@rakeshk15 It is not imported but shaded as part of the library. It is not optional in that sense, but is also not an actual external dependency.

Do you think there might be an easy change to OSGi metadata included via `pom.xml` to improve handling?

**Comment by rakeshk15** [comment] 2023-03-21 04:57
Hi @cowtowncoder,

I just saw the dependency being shaded and relocated as well, in that case we can omit the package from Import-Package header generated by maven-bundle-plugin.

Seems the <osgi.import> maven property is being used for Import-Package header declaration, if so, then the following statement can work.

<osgi.import>!ch.randelshofer.fastdoubleparser, *</osgi.import>

Unfortunately, I don't have the Jackson repos checked out at this moment, therefore, I am unable to try this locally.

Can you please try this and share the artifact with me so that I could test it?

Thanks,
Rakesh

**Comment by pjfanning** [comment] 2023-03-21 10:29
I don't know anything about osgi. There is nothing obvious in the jackson-core jar. I can't see any residual ch.randelshofer directories - the shading has moved all the classes to com.fasterxml... packages.

**Comment by pjfanning** [comment] 2023-03-21 10:32
@rakeshk15 we really need someone with osgi to help. Could you help? Checking out a git repo, making your `<osgi.import>` mod and rebuilding are easy.

**Comment by rakeshk15** [comment] 2023-03-21 10:47
ok, let me checkout the repos then.

**Comment by rakeshk15** [comment] 2023-03-21 10:58
I quickly checkout out/build/deploy the repo and found the fix i mentioned above working fine.

@pjfanning if you are a contributor to the repo then please add this line in the pom.xml just below <osgi.export></osgi.export> section somewhere around L54 

<osgi.import>!ch.randelshofer.fastdoubleparser, *</osgi.import>

This will fix the issue.

**Comment by pjfanning** [comment] 2023-03-21 11:11
Thanks @rakeshk15 - I created #957

**Comment by cowtowncoder** [comment] 2023-03-22 02:48
Merged #957.

@rakeshk15 I also deployed `2.15.0-rc2-SNAPSHOT` to Sonatype OSS nexus (you can build it locally as well) -- would it be possible for you to verify the issue is resolved? Fix makes sense but it'd be good for someone else to verify.

**Comment by cowtowncoder** [comment] 2023-03-22 03:03
Assuming resolved but will re-open if turns out there are remaining issues.

**Closed** 2023-03-22 03:03 UTC

**Comment by rakeshk15** [comment] 2023-03-22 04:37
@cowtowncoder i just tested 2.15.0-rc2-SNAPSHOT and I can confirm that it works. Bundle is active.

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/22319808/226803419-eef9d0e1-f99f-4c1e-a118-961fada69521.png">

**Comment by cowtowncoder** [comment] 2023-03-22 19:53
Thank you @rakeshk15 both for reporting this issue so quickly -- so we could get it fixed for 2.15.0! -- and follow-up.
