### ISSUE TITLE
JsonParser fails to parse valid numbers at top-level if they are immediately followed by invalid characters

### ISSUE THREAD

**Issue by andylowry-ibm** [FasterXML/jackson-core#930] opened 2023-02-27 16:27 UTC
JsonParser fails to parse top-level numbers that are immediately followed by a character (like a comma) that cannot appear at that point in the number. For non-numeric types this is not true: the value is parsed, and then a subsequent attempt to parse another value in the stream throws `JsonParseException`.  I'm guessing the difference is that in the numeric case the parser must peek at following characters to detect the end of the number, whereas that is not needed in all other cases.

It seems preferable for the parser to deliver a valid value that is at the front of its input, regardless of what follows. And if what follows is invalid for the start of a new JSON value, a subsequent parse attempt should fail.

Here's a short Java program that demonstrates the problem, which appears in the latest (2.14.2) published version.

```
package x;

import java.io.IOException;

import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Foo {
    private static ObjectMapper mapper = new ObjectMapper();
    private static JsonFactory factory = new JsonFactory();

    public static void main(String[] args) throws IOException {
        System.out.println("Parser version: " + factory.createParser("").version());
        tryParse("1,");
        tryParse("1 ,");
        tryParse("3.5,");
        tryParse("3.5 ,");
        tryParse("\"hello\",");
        tryParse("true,");
        tryParse("false,");
        tryParse("null,");
        tryParse("{\"a\": 1},");
        tryParse("[1,2,3],");
    }

    private static void tryParse(String s) throws IOException {
        System.out.println("===================== Parsing: " + s);
        JsonParser parser = factory.createParser(s);
        parser.setCodec(mapper);
        while (true) {
            try {
                JsonNode value = parser.readValueAsTree();
                if (value == null) {
                    break;
                }
                System.out.println("Parsed value: " + value);
            } catch (JsonProcessingException e) {
                System.out.println("Failed to parse: " + e.getMessage());
            }
        }
    }
}
```

If you run this program you'll see that inputs `"1,"` and `"3.5,"` both fail to yield any successfully parsed value, while `"1 ,"` and `"3.5 ,"` both report the initial value before failing on the subsequent parse attempt. All other cases show that other primitives, as well as structured values, can be parsed despite being immediately followed by a comma.

**Comment by andylowry-ibm** [comment] 2023-02-27 17:20
My apologies... I got confused by a lexographically sorted version list when browsing maven central.

Same result with 2.14.2. I've updated my original comment with code that now prints the parser version number, and the program output now includes:
```
Parser version: 2.14.2
```

Otherwise all is as originally reported.

**Comment by pjfanning** [comment] 2023-02-27 18:35
I'll leave it to @cowtowncoder to decide if there is any impetus to update the code here. jackson-core is really for parsing JSON and other structured formats like binary JSON, XML, TOML, etc. Parsing plain text to numbers is probably not the priority, even if it kind of works. The JDK provides methods to parse plain text to numbers, eg `Double.parseDouble` - could you use those methods?

**Comment by andylowry-ibm** [comment] 2023-02-28 01:23
Thanks @pjfanning. My use-case is quite a bit more complicated than parsing numbers, and of course, numbers **are** JSON values, so it seems reasonable to expect a JSON parser to handle them similarly to how it handles any of the other value types. I'll admit that this is probably not something that will rate a high priority in most circles, but it also may be quite simple (something like backing up the end-of-buffer pointer for the internal buffer so the bad char will be re-visited on next parse?). So maybe the most likely way to get it addressed is for me to take a crack at it if there are no objections.

FWIW, my use case is one where we have a need to parse large arrays of JSON objects that appear on a single line in a file. The array was formerly parsed as a string read from a BufferedReader. But the lines are now getting too large for that (> 2 billion chars in some installations), so we're revising. The unfortunate choice of one huge array is one we'll have to live with for backward compatibility for quite some time.

One approach is to just parse the array directly from the input stream without first isolating the line on which it appears and presenting it as a string. But that ends up being quite slow, and the parsed JsonNode tree can consume quite a lot of memory. A much leaner approach, albeit very hack-ish, is to edit the top-level array syntax (brackets, commas, and whitespace surrounding those) out of the input stream as it's read, and feed the result to the streaming parser. We formerly used Gson, but for this to work, we're switching to Jackson because of JsonParser's `releaseBuffer(OutputStream)` method, which allows us to push unused buffered data back onto the input stream between parses. That way we get to do stream editing to discard any top-level array syntax at the front of the input stream prior to asking the parser to do the next parse. This works great. It the effect of elevating the array elements to top-level in the edited input so that `JsonParser` can just stream out the parsed objects for downstream processing. It performs much better than the aforementioned whole-array parse.

In truth, we don't really need to worry about the problem I've reported, because everything in this huge array is a JSON object - no numbers at top-level in the array. It's mostly just bothering me that it won't work uniformly for all JSON values, and I only discovered it due to a unit test that was testing all the JSON value types.

So like I said, if there's no objection, I may take a crack at this and see if it's indeed as straightforward as I'm imagining it to be. Let me know.

**Comment by cowtowncoder** [comment] 2023-02-28 01:35
Also, fwtw, I do see possible confusion wrt white-space separation: that may seem arbitrary.
But the intent really is to allow/require white-space separation at main (root) level; and with that tokenization behavior (if this did work for all tokens...) is similar to that of nested values, just using different separator character(s).

Be that as it may, this is the intended default behavior. As usual, if someone had time and interest, I would accept PR for alternate configurable behavior for, say, `JsonReadFeature.LAZY_ROOT_VALUE_DECODING_ERRORS`, enabling of which would defer throwing of exceptions.

**Comment by cowtowncoder** [comment] 2023-04-11 00:53
As per my comment this is working as intended. I am open to configurable alternate handling, as usual; but will close this particular issue as no immediate work is planned (happy to help others with PRs, but from my own plans).

**Closed by cowtowncoder** 2023-04-11 00:53 UTC
