### ISSUE TITLE
how to disable InternCache.intern

### ISSUE THREAD

**Issue by huskyui** [FasterXML/jackson-core#998] opened 2023-04-25 08:12 UTC
we now use jackson  version `2.12.3` 

yesterday ,when my server occurs oom problems.
we  dump thread,  found 1549 blocked thread. 
1450 of the 1549 blocked threads are blocked in `InternCache.java:53`
```
stackTrace:
java.lang.Thread.State: BLOCKED (on object monitor)
at com.fasterxml.jackson.core.util.InternCache.intern(InternCache.java:53)
```

we try this solution,but fail
```
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.getFactory().configure(JsonFactory.Feature.INTERN_FIELD_NAMES, false);
```

please tell me how to fix this problem

**Comment by huskyui** [comment] 2023-04-25 11:46
> could you provide more of one of the blocked stacktraces so we can see what code is in the call path?
> 
> it may be worth trying a newer version of Jackson but that is not guaranteed to changed things.

here is an example
```
stackTrace:
java.lang.Thread.State: BLOCKED (on object monitor)
at com.fasterxml.jackson.core.util.InternCache.intern(InternCache.java:53)
- waiting to lock <0x00000006b7329168> (a java.lang.Object)
at com.fasterxml.jackson.databind.PropertyName.internSimpleName(PropertyName.java:114)
at com.fasterxml.jackson.databind.deser.SettableBeanProperty.<init>(SettableBeanProperty.java:153)
at com.fasterxml.jackson.databind.deser.SettableBeanProperty.<init>(SettableBeanProperty.java:136)
at com.fasterxml.jackson.databind.deser.impl.FieldProperty.<init>(FieldProperty.java:46)
at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.constructSettableProperty(BeanDeserializerFactory.java:885)
at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:582)
at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:277)
at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:150)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
- locked <0x00000006dd8a0880> (a java.util.HashMap)
at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:558)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:188)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:28)
at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:765)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:550)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
- locked <0x00000006dd8a0880> (a java.util.HashMap)
at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:591)
at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4733)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4594)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3531)
at com.ly.mp.resourcefrontend.common.utils.JsonUtils.string2GenericAbstract(JsonUtils.java:136)
at com.ly.mp.resourcefrontend.modules.scenery.service.scenery.impl.ResourcePolicyCacheServiceImpl.getScreenPolicyInfoListByCache(ResourcePolicyCacheServiceImpl.java:90)
at com.ly.mp.resourcefrontend.modules.scenery.service.scenery.impl.ResourcePolicyCacheServiceImpl$$FastClassBySpringCGLIB$$3eceef34.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:49)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
at com.ly.mp.resourcefrontend.modules.scenery.service.scenery.impl.ResourcePolicyCacheServiceImpl$$EnhancerBySpringCGLIB$$6f23f5f2.getScreenPolicyInfoListByCache(<generated>)
at com.ly.mp.resourcefrontend.modules.scenery.service.scenery.impl.ResourcePolicyServiceImpl.getFrontDestResourcePolicyInfos(ResourcePolicyServiceImpl.java:431)
at com.ly.mp.resourcefrontend.modules.scenery.service.scenery.impl.ResourceProductMergeImpl.getSceneryProductListResponseResult(ResourceProductMergeImpl.java:1013)
at com.ly.mp.resourcefrontend.modules.scenerylistsingleserver.service.impl.SingleServerServiceImpl.getMinPriceInfoForList(SingleServerServiceImpl.java:285)
at com.ly.mp.resourcefrontend.modules.scenery.service.scenery.impl.SceneryListServiceImpl.lambda$null$523(SceneryListServiceImpl.java:508)
at com.ly.mp.resourcefrontend.modules.scenery.service.scenery.impl.SceneryListServiceImpl$$Lambda$1837/2127609470.get(Unknown Source)
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:59)
at com.ly.tcbase.apm.agent.plugin.etc.ExecutorServiceInterceptor$ProxyRunnable.run(ExecutorServiceInterceptor.java:92)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by pjfanning** [comment] 2023-04-25 12:01
that code path does not check JsonFactory.Feature settings - those settings are more for jackson-core code than for the jackson-databind code that this affects

@cowtowncoder would it make sense to introduce a DeserializationFeature like the JsonFactory.Feature.INTERN_FIELD_NAMES ?

**Comment by pjfanning** [comment] 2023-04-25 12:04
@huskyui I'm not sure if interning strings will lead to OutOfMemory issues but generally once you start running close to have OOM issues, everything starts going wrong.

In the end of the day, you might need to increase your Xmx setting of throttle your code so that you don't have so many threads trying to do memory intensive work at the same time.

**Comment by huskyui** [comment] 2023-04-25 12:08
> @huskyui I'm not sure if interning strings will lead to OutOfMemory issues but generally once you start running close to have OOM issues, everything starts going wrong.
> 
> In the end of the day, you might need to increase your Xmx setting of throttle your code so that you don't have so many threads trying to do memory intensive work at the same time.

got it.

**Comment by cowtowncoder** [comment] 2023-04-25 17:16
@pjfanning I think the issue is that part of code calling `InternCache.intern()` has no access to configuration settings, including `DeserializationFeature`. Ideally it should definitely look for existing feature.

**Comment by cowtowncoder** [comment] 2023-04-25 17:20
@huskyui I think you have some other problem wrt not reusing `ObjectMapper` instances or something -- this should not become a hotspot, ever. There should not be need to create deserializers concurrently for thousand(s) of threads. Usually locking in this place is a symptom, not the root cause.

If I had to guess, I'd look into

    JsonUtils.string2GenericAbstract(...)

to see if it might be actually creating new `ObjectMapper` for every call?
If so, that's EXTREMELY inefficient and the main problem. So even if `InternCache` didn't lock, it'd probably have other performance issues about as severe.

**Comment by huskyui** [comment] 2023-04-26 02:00
> @huskyui I think you have some other problem wrt not reusing `ObjectMapper` instances or something -- this should not become a hotspot, ever. There should not be need to create deserializers concurrently for thousand(s) of threads. Usually locking in this place is a symptom, not the root cause.
> 
> If I had to guess, I'd look into
> 
> ```
> JsonUtils.string2GenericAbstract(...)
> ```
> 
> to see if it might be actually creating new `ObjectMapper` for every call? If so, that's EXTREMELY inefficient and the main problem. So even if `InternCache` didn't lock, it'd probably have other performance issues about as severe.

```
    public static <T> T string2GenericAbstract(String json, TypeReference<T> typeReference) throws Exception {
        if (json == null || json.isEmpty()) {
            return null;
        }
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.getFactory().configure(JsonFactory.Feature.INTERN_FIELD_NAMES, false);
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        objectMapper.setTimeZone(TimeZone.getTimeZone("GMT+8"));
        return objectMapper.readValue(json, typeReference);
    }
```

**Comment by cowtowncoder** [comment] 2023-04-27 03:31
Ha! Called it. :)

@huskyui your problem is that creation of `ObjectMapper` for every call -- depending on size of input, reuse could be 10-20x faster than code as-is. Contention for `InternCache` is just a side effect of this extremely wasteful handling and is not the cause but symptom.
So you should try to figure out how to reuse it: a simple `private static final ObjectMapper` often works fine; or if you really want, dependency-injected instance.

@pjfanning This is something I have found time and again: before starting to consider interning/canonicalization as an actual problem it is necessary to first rule out more likely explanations of performance issue. The fact is that `ObjectMapper` is very expensive to create for one-offs (one exception may be `ObjectMapper.readTree()` which "only" has about 100% overhead for small input) and there's no way to really optimize that case.

I will close this issue as the problem has been identified as far as I know.

**Closed by cowtowncoder** 2023-04-27 03:31 UTC

**Comment by huskyui** [comment] 2023-04-27 05:41
@cowtowncoder thx.
