### ISSUE TITLE
Improve error report on non-static inner class deserialization

### ISSUE THREAD

**Issue by ekis** [FasterXML/jackson-core#226] opened 2015-10-30 19:32 UTC
#### Summary ####
Recently I had a run in with a long-standing feature (?) of Jackson which is essentially - Jackson doesn't know how to deserialize non-static inner class, as the class relies on compiler trickery to provide reference to the outer class and doesn't have an public no-arg constructor (details may be found [here](http://www.cowtowncoder.com/blog/archives/2010/08/entry_411.html)). I didn't test if a custom deserializer would help in this case.

Jackson (2.6.1) throws a uninformative exception `java.lang.IllegalArgumentException: Unrecognized Type: [null]` which defeats the principle of least astonishment - the only reason I was able to even assume what was going on was incindental: I was doing some refactoring which touched POJOs which I _knew_ were working from the day before. As a part of my refactoring I removed a static class modifier from POJO's inner class and marched on - the next day I ran tests and was faced with the error. Even with such a recent knowledge it was not trivial to track down what was causing this error and why - actually, I happened to stumble upon the answer by a fluke: I just happened to add back the static modifier *sure* that it still wouldn't work; I was very surprised it did.

Since it was so hard to understand why it failed, I dug into the Jackson codebase a little bit, have a proposal and would like your feedback on it.

#### Cause ####
The message is constructed by TypeFactory class in this code segment - the `sanity check` comment is the block where the actual error message is crafted:

The call stack leading to this point is this: `DeserializerCache -> BeanDeserializerFactory -> BasicDeserializerFactory -> TypeFactory`.

    protected JavaType _constructType(Type type, TypeBindings context)
    {
        JavaType resultType;

        // simple class?
        if (type instanceof Class<?>) {
            resultType = _fromClass((Class<?>) type, context);
        }
        // But if not, need to start resolving.
        else if (type instanceof ParameterizedType) {
            resultType = _fromParamType((ParameterizedType) type, context);
        }
        else if (type instanceof JavaType) { // [Issue#116]
            return (JavaType) type;
        }
        else if (type instanceof GenericArrayType) {
            resultType = _fromArrayType((GenericArrayType) type, context);
        }
        else if (type instanceof TypeVariable<?>) {
            resultType = _fromVariable((TypeVariable<?>) type, context);
        }
        else if (type instanceof WildcardType) {
            resultType = _fromWildcard((WildcardType) type, context);
        } else {
            // sanity check
            throw new IllegalArgumentException("Unrecognized Type: "+((type == null) ? "[null]" : type.toString()));
        }
        if (_modifiers != null && !resultType.isContainerType()) {
            for (TypeModifier mod : _modifiers) {
                resultType = mod.modifyType(resultType, type, context, this);
            }
        }
        return resultType;
    }

#### Proposal ####
There is no way to check if a class is static so low in the stack, the earliest spot I could find where we could perform the check would be be before finding value instantiator in `BasicDeserializerFactory.findValueInstantiator()`.

The simple fix would be something along these lines:

```
if (!Modifier.isStatic(type.getRawClass().getModifiers())) {
   throw new IllegalStateException("Inner class must be static - Jackson cannot create it.");
}
```

Alternative would be to pass down the call stack JavaType object and then do this check in `_constructType()`.

I am not an expert on Java Reflection API, so there may be a better solution. If you think this is good enough but don't want to be bothere with this, I'd be happy to fork it, apply the changes and make a pull request.

Let me know what you think.

**Comment by cowtowncoder** [comment] 2015-10-31 20:57
@ekis First of all I fully agree in that such error message is useless and would be good to improve.
Second of all, I think the best starting point could be a (failing) unit test that gives an example -- I realize it is easy to reproduce, but it's still nice to have simple test to use for verification.

One practical issue right now, however, is this: I am finally rewriting type introspection for Jackson 2.7, to resolve long-standing issues with type aliasing (binding of type variables varies between classes within type hierarchy; but Jackson up to 2.6 only has per-resolution map of bindings). This is based on better type introspection of `java-classmate` that I wrote based on learnings from Jackson code.
This is all good in itself (tons of work, and not yet complete), but it does mean that code in this area will vary a lot between 2.6 and 2.7. Unit test should be reusable, but solving the problem is probably best started with current `master` (for 2.7); and then see if fix can be back-ported, or if not, rewritten to work for 2.6 patch.

**Comment by ekis** [comment] 2015-11-02 15:48
Sorry, I had forgotten to add the test. Tests are run using Jackson 2.6.1, registered ParameterNames and JDK8Module modules. Code is compiled with JDK 1.8 build 60 and `-parameters` option.

The following test will fail the mentioned exception unless:
1) all three classes are defined as `static`
2) no classes are defined as `static` but the type of `Inner.s2` field is changed to a primitive (i.e. String).

I couldn't discover or reason out the root cause of 2) - do you happen to know why this is occuring?

    @Test
    public void testStatic() throws IOException {
        String test = "{\n" +
                "\t\"task\" : {\n" +
                "\t\t\"outer\" : {\n" +
                "\t\t\t\"inner\" : {\n" +
                "\t\t\t\t\"s1\" : \"x\",\n" +
                "\t\t\t\t\"s2\" : \"y\"\n" +
                "\t\t\t}\n" +
                "\t\t}\n" +
                "\t},\n" +
                "\t\"array\" : [\"a\", \"b\"]\n" +
                "}";

        JsonParser parser = JacksonUtil.getMapper().getFactory().createParser(test);
        parser.nextToken();
        while (parser.nextToken() != JsonToken.END_OBJECT) {
            if (parser.getCurrentName().equals("task")) {
                parser.nextToken();
                parser.readValueAs(Task.class);
            } else if (parser.getCurrentName().equals("array")) {
                parser.nextToken();
                parser.readValueAsTree();
            }
        }
    }

    private final class Task {
        @JsonProperty private final Outer outer;

        @JsonCreator
        private Task(Outer outer) {
            this.outer = outer;
        }

        private final class Outer {
            @JsonProperty private final Inner inner;

            @JsonCreator
            private Outer(Inner inner) {
                this.inner = inner;
            }

            private final class Inner {
                private final String s1;
                private final Optional<String> s2;

                @JsonCreator
                private Inner(String s1, Optional<String> s2) {
                    this.s1 = s1;
                    this.s2 = s2;
                }
            }
        }
    }

**Comment by cowtowncoder** [comment] 2015-11-24 06:00
I don't know the exact reason, but since `String` is the "natural" type, anything declared as `java.lang.Object` would be deserialized from JSON String as Java String, including case where Type Erasure bites.

**Comment by ekis** [comment] 2015-11-24 15:49
OK, sir - I can take care of this but have this to ask: I've never actually forked a project and then made a pull request, so do you have a preferred way of doing this? What do you recommend?

Also, is there a code standard we should adhere to in Jackson? Any hints in that area?

**Comment by cowtowncoder** [comment] 2015-11-24 18:46
@ekis Help would be much appreciated!

The easiest way to work is probably by using github's "fork" button, work on changes, and then submitting a Pull Request (there's a button for that), which creates PR entry and lets us review, merge it.
Alternatively if diffs are minor, just including pieces in issue are fine, I can manually merge changes as well, whatever works best.

As to coding standard, my general philosophy is along "When in Rome, do as romans", i.e. follow the local style regarding indentation, naming. Code is relatively consistently styled, but not strictly so, and I do not run automated tools to enforce specific style. I do care about naming, but that should be easy enough to follow -- local variable names are less important, function/field naming more so. I can help if there are any things that need changing.

Things to avoid are... let's see.

* No tabs (all indentation by spaces). I trip into this due to Eclipse defaulting to tabs, Emacs following, so there may be feral tabs in some places. I'll euthanize such tabs gently when encountered.
* No auto-reformatting of large chunks of code that you do not touch -- mostly because it adds to diffs, so it's more work to see "real" functional changes. Reformatting within changed area is fine (to remove tabs, perhaps add missing space or extra, whatever). Some tools try to auto-format full files so that's probably why some patches have lots of fluff, indentation changes.

Other than that I am not superbly picky. Smallest patches are often nicer, easier to grok.

I try to help as well and sometimes do minor post-merge cleaning up, mostly for some code simplification for internal api usage.

**Comment by ekis** [comment] 2015-11-24 18:59
OK, I'll give it a shot this afternoon. Questions:
1) When doing a pull request, do I reference this issue number as a part of commit comment? What is the policy there?
2) Any preferred IDE? Are we using Ant, Gradle, Maven or something else for build? What do you suggest?

**Comment by cowtowncoder** [comment] 2015-11-25 15:58
@ekis 

* JDK6: Correct for now, despite JDK classes for JDK7 supported dynamically. For 2.8 will allow use of Java7 features (diamond pattern, multi-catch)
* Add hash-prefixed id somewhere in title or description (like referencing this issue would be #226), may add to commit if you want to, not mandatory but is useful. I often just do "fix N" for simpler ones; full description available in issue; but adding small sentence is nice too.
* Build, releases using Maven. I use Eclipse mostly, sometimes Idea; should not matter (no project files checked in, `.gitignore` tries to keep them out)

**Comment by cowtowncoder** [comment] 2016-05-07 00:49
With 2.7, error is now:

    "Non-static inner classes like %s can not use @JsonCreator for constructors"

which I think is adequate explanation, so closing.

**Closed by cowtowncoder** 2016-05-07 00:49 UTC
