### ISSUE TITLE
All attributes are deserialized when JsonView is used with inheritance

### ISSUE THREAD

**Issue by Handja** [FasterXML/jackson-core#431] opened 2017-12-13 16:46 UTC
Hello !

I use JsonView for deserialization but I encouter a problem with Inheritance.
If the first attribute of JSON object start is a parent attribute, jackson doesn't take care of views.
I need to add at least one attribute of my child class on first position.

Example : 

Child class

```
public class Child extends Parent implements Serializable {

        @JsonView(JsonViews.Creation.class)
        private String childA;

        @JsonView(JsonViews.Creation.class)
	private String childB;

	@JsonView(JsonViews.Edition.class)
	private String childC;
}
```

Parent class

```
public abstract class TestParent implements Serializable {

	private static final long serialVersionUID = 3668131924415053459L;

	@JsonView(JsonViews.Edition.class)
	private Long parentA;

	@JsonView(JsonViews.Creation.class)
	private Long parentB;

}

```

I use Views.Creation to deserialize.

Wrong behaviour (all attributes are deserialized), if JSON structure is : 

```
{
	"parentA": 1,
	"parentB": 2,
	"childA": "A",
	"childB": "B",
	"childC": "C"
}
```

Right behaviour (ParentB and ChildC are not deserialized), if JSON structure is :

```
{
	"childB": "B",
	"parentA": 1,
	"parentB": 2,
	"childA": "A",
	"childC": "C"
}
```

**Comment by cowtowncoder** [comment] 2017-12-13 21:17
Sigh. Ok. Couple of problems:

1. This issue would be against `jackson-databind` (this repo is only for streaming parser/generator)
2. Which Jackson version is this with? -- and please make sure you are actually using _latest patch_ of minor version you have -- patches contain important fixes
3. What code do you use to serialize content? (with what settings of `ObjectMapper` or `ObjectWriter`?

You may add info on (2) and (3) first since it is not possible (afaik) to move issues across repositories; perhaps I can suggest what is going on since there are no known open issues in view handling that I am aware of.

**Comment by Handja** [comment] 2017-12-14 10:19
Sorry for the missed informations

2. Version 2.8.10 and 2.9.3, test both.

3. I use @ViewJson on method parameter to deserialize (In controller).

' Hope that answered your questions :)

**Comment by cowtowncoder** [comment] 2017-12-14 23:49
@Handja that's part of it, but not (3). I don't know what `@viewjson` is; it's not something Jackson provides (maybe it's by some framework / lib?).

So basically I need a way to reproduce your problem, only using Jackson components. This because frameworks often add additional processing outside of Jackson and it is important to figure out where the problem occurs. I can only help with jackson parts.

**Comment by Handja** [comment] 2018-01-04 20:45
After a long time...
I did some tests

It's not @ViewJson but @JsonView
The cause isn't inheritance.

The first attribute on java class is always deserialized if it's the first attribute of JSON object.
It doesn't take care of json view.

**Example**

I use "Creation" view for the deserialization.

Java class : first attribute with "Edition" view :

```
public class Letter implements Serializable {

        @JsonView(JsonViews.Edition.class)
        private String A;

        @JsonView(JsonViews.Creation.class)
	private String B;
}
```

And JSON with same first attribute :

```
{
	"A": "A",
	"B": "B"
}
```

When I use Creation View (for deserialization), A is deserialized, but it shouldn't.

**Comment by cowtowncoder** [comment] 2018-01-04 21:49
At this point all I need is a unit test that reproduces the problem. Otherwise I can not see what is going wrong. And then we can move the issue under `jackson-databind`.

**Comment by cowtowncoder** [comment] 2018-01-23 23:17
Needs both more info, and get moved to `jackson-databind`. May be refiled there, closing here.

**Closed by cowtowncoder** 2018-01-23 23:17 UTC
