### ISSUE TITLE
BigDecimalParser.parse very slow

### ISSUE THREAD

**Issue by sirnple** [FasterXML/jackson-core#1153] opened 2023-12-05 09:07 UTC
jackson-core version: 2.15.1

I have code like this, that can't finish in time:
```java
BigDecimal result = BigDecimalParser.parse("\u000133000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0017\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0017\u0017\u0017\u0017\u0017\u0017\u0017\u0017\u0017\u0017\u0017\u0017\u0017\u0017$\u0017\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\t\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000z\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0017\u0017\u0017\u0017\u0017nn\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000nn\u0017\u0017\u0017\u0017\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001 \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0000|\u0000\u0000\u0000\u0000\u0000000000000000000002222222222330000000000000000000000000000003330000000003333322222222222222222222222222222222222222222222222222222222330000000000000000222222222222222222222222\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0017\u0017\u0017\u0017\u0017\u0000\u0000\u0000\u0000\u0000\u0000\u0017\u0017\u0017\u0017\u0017\u0017\u0017\u00000\u0017+.2222222222222222222222222222222222E222222242");
```
I have checked issue list, and I found many performance improvement, but my input still trigger an slow parse. 

Additional：this input is produced by fuzz test.

**Comment by pjfanning** [comment] 2023-12-05 10:23
Parsing BigDecimals is slow. Performance is much worse than O(n). There is not much that can be done to make it fast. Use your favourite search engine to seek out the literature.

You might find that BigDecimalParser.parseWithFastParser is a little faster.

BigDecimalParser.parse uses the built-in Java BigDecimal code while BigDecimalParser.parseWithFastParser uses https://github.com/wrandelshofer/FastDoubleParser

BigDecimalParser is really an internal Jackson class and it is not recommended that it is used directly.

Jackson is built to parse and write JSON (and via modules some other formats like XML and CSV). If you use a Jackson ObjectMapper, the most recent versions of Jackson limit the size of number that it will parse. This can be tweaked but the reason to limit the number of chars that Jackson will parse for numbers is precisely because of the risk that a malicious JSON file could have a very long number string in it.

**Comment by pjfanning** [comment] 2023-12-05 12:06
@sirnple I think you have found a bug in `BigDecimalParser.parse`. I tried the fuzz value with `new BigDecimal`, `BigDecimalParser.parseWithFastParser`, etc. and these fail quickly due to this being an invalid number.

`BigDecimalParser.parse` is much slower. That code breaks up the string into smaller pieces but this string causes issues.

**Comment by cowtowncoder** [comment] 2023-12-06 00:04
Ok, so there may be an issue somewhere, but as @pjfanning said, `BigDecimalParser` is NOT part of public API -- it is not to be used directly by code outside Jackson-core but only indirectly via parsing API.
So in that sense reproduction is not useful in itself. I may close the issue in near future.

But if there is a way to trigger the issue through API that'd be different story.
So leaving this open for the moment.

**Comment by cowtowncoder** [comment] 2023-12-08 00:05
Since I think this issue itself is not necessary valid (wrt passing invalid numbers), I'll close it -- but it did spawn #1157 to address possibly relevant case so it's good this was filed.

**Closed** 2023-12-13 01:05 UTC
Labels: performance
