### ISSUE TITLE
CharsToNameCanonicalizer performance bottleneck

### ISSUE THREAD

**Issue by nmldiegues** [FasterXML/jackson-core#349] opened 2017-01-27 14:52 UTC
Summary: While deserializing JSON Strings in concurrent threads with Jackson, we soon realized that there was a sequential bottleneck preventing throughput from scaling up. **Upon profiling, the culprit seems to be the synchronized block in CharsToNameCanonicalizer#makeChild(int)** that gets called on every _createParser method (which is happening once per deserialization).

Details: To prove this point, we ran a simple test with a ThreadLocal<ObjectMapper> per thread deserializing in comparison with a single ObjectMapper shared across the threads.
On my laptop with 8 cores (4 physical, 8 logical) we had:

- 1 thread  : 35k/sec for both
- 2 threads: 55k/sec for shared, 66k/sec for thread-local
- 4 threads: 70k/sec for shared, 120k/sec for thread-local
- 8 threads: 45k/sec for shared, 150k/sec for thread-local

Upon profiling with YourKit, it quickly identified the monitor held in CharsToNameCanonicalizer#makeChild(int) as the blocker for the threads, preventing them from processing the data concurrently --- as otherwise, if it was not for Jackson, there would be no dependency at all among the threads in this simple example (they should be embarrassingly parallel).

![image](https://cloud.githubusercontent.com/assets/889015/22374913/f9e36168-e49f-11e6-84a8-caa3973341f2.png)

We are using the typical ObjectMapper#readValue approach, and also tried the ObjectReader approach --- which leads to a similar code path of instantiating a JsonParser.
It did not seem obvious at all that we can reuse JsonParsers across different JSON objects, but if so then that could be a way around this.

In any case, we believe we are doing things in the way suggested across the documentation, so even if this does not lead to code changes, it should lead to documentation improvements as to how best avoid sequential bottlenecks when sharing ObjectMappers.

**Comment by cowtowncoder** [comment] 2017-01-28 19:12
Quick question: which version of Jackson are you using?

**Comment by nmldiegues** [comment] 2017-01-28 19:18
Good point: 2.4.2

**Comment by cowtowncoder** [comment] 2017-01-28 22:18
@nmldiegues I would strongly suggest trying out a later version since I believe there were some  some synchronization improvements in this area. Even just 2.4.6 (latest 2.4.x) might help, but definitely 2.6(.7) or later should be up to date in this respect. 
I just want to make sure that what you are seeing is still occurring.

**Comment by nmldiegues** [comment] 2017-01-28 22:25
Thanks for the pointers; I will check those out in the upcoming days.

**Comment by nmldiegues** [comment] 2017-01-30 17:45
I've tested 2.6.1, 2.6.7 and 2.8.6 and the results where the same.

**Comment by cowtowncoder** [comment] 2017-01-30 18:17
@nmldiegues Ok. There is no real way around this. `JsonParser` instances are not designed reusable, but even if they did, symbol table life cycle should span over multiple uses. I would be interested in knowing why this should become actual and not potential bottleneck, as it really seems like a rather small critical section. And whether it could be improved by use of some other synchronization method.

**Comment by cowtowncoder** [comment] 2017-01-31 19:47
Couple more questions here, if you don't mind, regarding processing situation:

1. Are documents being processed very small? (or what is typical size per document)
2. Is set of property names bounded (more or less fixed, field names) or unbounded (generated JSON object field names, like UUIDs, sequence numbers)?
3. What level of concurrency is being observed/tested, as rough order of magnitude? (10, 100, 100s, 1000s of threads?)

**Comment by nmldiegues** [comment] 2017-01-31 20:30
Absolutely, feel free to ask:

1. Average 1KB (not sure what you'd consider very small)
2. Yes, bounded (and not that large, I guess around 100-ish)
3. I mentioned it in the example: since I have 8 cores, I tested up to 8 on this micro-benchmark. But on our use case it can grow up to 100.

**Comment by cowtowncoder** [comment] 2017-01-31 20:40
@nmldiegues Ah sorry: by small I would mean like.... tiny. Like a single JSON Object with couple of scalar properties. 1kB would not be particularly small.

Hmmh. Ok. I certainly would not expect any actual performance bottlenecks with lowish (test) concurrency. But numbers you mentioned earlier would suggest real problem.
What I find odd is that I have never seen anything quite drastic, with jmh tests.

If I find time I hope to see if I can reproduce similar findings, `jmh` makes it simple to parallelize and I have beefy enough desktop so I should see something.

**Comment by cowtowncoder** [comment] 2017-02-01 06:33
@nmldiegues Ahh! One thing I hadn't noticed was that this affects `CharsToNameCanonicalizer`and not byte-based variant `ByteQuadsCanonicalizer`. Looking at implementations, latter did indeed improve `makeChild` by separating relevant state into a helper object, and synchronizing only on that. The other relevant method being `mergeChild`.
I'd be willing to bet that this makes a big difference, and that similarly improving `CharsToNameCanonicalizer` by refactoring would help.

If my speculation is correct this would also explain why I have not seen problems with multi-threaded cases because most of my performance testing has been on byte-backed data (it being the most efficient way, end-to-end). I do have tests for char-based version too, and I have sometimes run them, but not by varying concurrency I think.

Now... I may not have time right now to work on this, but could help if anyone wants to take a stab at improvements. I am mildly worried about small but existing chance of getting into other problems (if added in a patch, most likely just for 2.8.x), as concurrency can be hard thing to get right. But since there is known working pattern (byte-based alternative has been solid for multiple versions, regarding concurrency) risk should be quite low.

**Comment by cowtowncoder** [comment] 2017-02-14 00:28
@nmldiegues Ok, finally found time to do some local profiling with `jackson-benchmarks` which uses `jmh` and allows configurable number of threads.

Results using `2.8.6` (which is not all that different from 2.6 or later as far as I recall) are bit mixed.

On one hand, throughput tests between char-based ones (that you are using) and byte-based ones do not show significant difference for me: my desktop (alleges to have 8 cores, not sure if that refers to actual or logical ones) has similar scalability so that 10 threads has about 6x throughput of single-threaded test. Char-based input is slightly slower to process (Jackson is optimized for byte input), but not by much (~10%).
So I can not really see actual performance difference there.
This with JVM 1.8.0_112.

However: when using profiler (slice-sampling based, default Xhprof), I do see difference, so that on char-based one (and only that!) profiler claims 34% time spent on `makeChild`; for byte-backed variant I have to dig deep down to see 0.02%.

But I really wonder if this isn't just profiler artifact: assuming there are 8 threads of execution max (from cores), 25% of threads will need to wait for CPU, and where this occurs may not matter a whole lot. I based this on fact that throughput does not really vary -- I tried it with higher thread counts as well; at 20 throughput is slightly lower than with 10, but not by much, and ratios between input modes are still identical.

So. I may still work on improving this, as there is no real upside to longer locking. But I am not seeing actual performance issue at this point.

**Comment by cowtowncoder** [comment] 2017-02-14 21:55
Ok, I changed code in `CharsToNameCanonicalizer` to use similar technique for removing need for `synchronized`, which removes stack trace on my local `jmh` test.
I hope it helps with the problem you see; for me there is no increase in throughput, but then again I also did not see original performance problem. It is possible test setup has some difference; if `jmh` did actually use separate processes instead of threads (or, possibly, different class loaders?) that could do it.

Anyway the change will be in 2.8.7 and I would be interested in knowing if it changes concurrency aspects.

**Closed by cowtowncoder** 2017-02-14 21:55 UTC

**Comment by nmldiegues** [comment] 2017-02-15 09:22
Thanks a lot for looking into this once again. I will allocate time to re-test this as soon as possible, but it can be a few days before I can switch back to this context.

**Comment by cowtowncoder** [comment] 2017-02-16 18:31
@nmldiegues Understood. Whenever you have time, would be interested in whatever you find.

**Comment by nmldiegues** [comment] 2017-02-17 23:27
@cowtowncoder good news, the patch seems to have had the desired effect:

2.8.7-SNAPSHOT
1 thread : 40k/sec for both
2 threads: 80k/sec for shared, 75k/sec for thread-local
4 threads: 133k/sec for shared, 136k/sec for thread-local
8 threads: 156k/sec for shared, 155k/sec for thread-local

So the results are the same regardless of the threads sharing the ObjectMapper or having 1 per thread.

From what I can tell this is a great improvement, thanks!

**Comment by cowtowncoder** [comment] 2017-02-18 01:07
@nmldiegues Great! Surprising that effect is so big, but glad to hear improvement is real.
